### ISSUE TITLE
Works in singleplayer but not in multiplayer

### ISSUE THREAD

**Issue by Carnage15** [Draylar/inmis#101]
Backpacks works fine in single but i can´t even craft them in multiplayer.

**Comment by AryonLegacy** [comment]
is mod installed on the server?

**Comment by Carnage15** [comment]
Yes, both on server and client.

**Comment by AryonLegacy** [comment]
Make sure you server is using Fabric 1.18 jar and you have 1.18 Fabric API in mods folder along with INMIS. If thats not the issue then it must be incompatibility with other mods or smt idk

**Comment by Draylar** [comment]
Can you [send your game logs](https://minecrafthopper.net/help/guides/getting-minecraft-game-output-log/) for the server? Thanks!

**Comment by Carnage15** [comment]
I fixed it, it works fine now.
