### ISSUE TITLE
Suggestion: trinkets, hotkey and visualization

### ISSUE THREAD

**Issue by MJRamon** [Draylar/inmis#104]
Trinkets support would be very nice.

As well as visualization of backpack on player's back and a hotkey (B, for example).

**Comment by Draylar** [comment]
Trinkets is actually already supported in recent versions - you can put Backpacks in your backpack slot and press the B key to access it (perfect prediction)!

---

I love the idea of backpack visualization, so I've added it in the next release... it's a bit of a budget solution given my lack of modeling skills, but I think it still looks much better than nothing. It supports backpacks in the Trinkets & Armor slot. This will be out in the next release, so let me know what you think! Thanks for the suggestions.

![image](https://user-images.githubusercontent.com/17728338/150008522-5a345033-1d16-452d-a772-b18e86830fb7.png)

**Comment by MJRamon** [comment]
That's great news!

Actually, I've modelled and textured a backpack in Blockbench:
![image](https://user-images.githubusercontent.com/2642227/150013048-7ce2192b-3ac2-41e4-9c97-8dd3fe594e16.png)

It's only a leather variant, but you can use it for Inmis and re-texture as you like.
[backpack.zip](https://github.com/Draylar/inmis/files/7892168/backpack.zip)
