### ISSUE TITLE
Backpack slots use Hopper

### ISSUE THREAD

**Issue by Baxmann** [Draylar/inmis#121]
But, why? Why not Generic? 

My texture pack was having a weird effect due to using the hopper on the Backpack GUI.

**Comment by Draylar** [comment]
The 2.6.0 version of Inmis from the beginning of this month ships a unique texture file [at this location](https://github.com/Draylar/inmis/blob/1.18.2/src/main/resources/assets/inmis/textures/gui/backpack_slot.png), which should solve your problem.

**Comment by Baxmann** [comment]
I see now. So since the modpack I use is from 1.18.1, and the 2.6 only came out on 1.18.2, and 1.18.1 has 2.5, then the problem will persist until the modpack updates to 1.18.2.

Thanks for helping me with that. Keep up the good work.
