### ISSUE TITLE
Shift clicking items into backpack does not stack correctly sometimes.

### ISSUE THREAD

**Issue by calloatti** [Draylar/inmis#14]
![image](https://user-images.githubusercontent.com/12817862/82735623-64ca7100-9cf9-11ea-8b8b-bcc230d19392.png)

If you shift click the iron nuggets in the red circle, and you have an empty slot in the backpack, this happens:

![image](https://user-images.githubusercontent.com/12817862/82735628-6c8a1580-9cf9-11ea-840d-026bd73c64bc.png)

This should happen instead:

![image](https://user-images.githubusercontent.com/12817862/82735648-888db700-9cf9-11ea-8789-9379e39b1c0e.png)

**Comment by Draylar** [comment]
This is a Spinnery issue, so I'm just waiting on the newest version to be pushed (as it has been fixed, but not uploaded yet).

**Comment by Draylar** [comment]
![image](https://user-images.githubusercontent.com/17728338/84304093-a2166780-ab1d-11ea-8799-7e3112a5fe96.png)

**Comment by Draylar** [comment]
Fixed in 1.3.0 thanks to shedaniel porting the GUI to vanilla~
