### ISSUE TITLE
The whole hotbar gets locked when opening a backpack

### ISSUE THREAD

**Issue by calloatti** [Draylar/inmis#15]
I want to click and drag the boat to the slot that has the iron nuggets, and then move the iron nuggets elsewhere, but the hotbar slots are locked, so I have to drag to boat to another slot, then close the backpack and only then I can move the boat to a hotbar slot.

![image](https://user-images.githubusercontent.com/12817862/82735710-fcc85a80-9cf9-11ea-8bf0-828a8c21d125.png)

If the idea is to prevent the moving of the backpacks while they are opened, maybe locking the whole hotbar seems like overkill, just lock the opened backpack slot.

**Comment by Draylar** [comment]
Spinnery issue, fixed in 2.1.2-beta.
