### ISSUE TITLE
Minecraft 1.20(.1)

### ISSUE THREAD

**Issue by Chucky2401** [Draylar/inmis#158]
Hello,
Do you plan to update this awesome mod to Minecraft 1.20(.1)?

**Comment by bigenergy** [comment]
https://www.curseforge.com/minecraft/mc-mods/inmis-renewed

**Comment by Chucky2401** [comment]
Thank you! I will give it a try!

**Comment by enderprism** [comment]
it isn't compatible with 1.20.x, or at least isn't explicit about it:
![image](https://github.com/Draylar/inmis/assets/76617157/09bfc171-cc4b-462a-b71c-4a994b629ee6)

**Comment by Globox1997** [comment]
Updated it to 1.20. Will be released shortly.

**Comment by bigenergy** [comment]
I definitely had to make a port so that the developer would wake up, classic, lol.
