### ISSUE TITLE
Bug that deletes everything you have in a backpack

### ISSUE THREAD

**Issue by calloatti** [Draylar/inmis#16]
https://www.youtube.com/watch?v=T9VemPs_Ys0

**Comment by Draylar** [comment]
I can't reproduce this fully, but I _have_ seen it occur. I took the exact same steps as you did in the video with no luck, but then I saw it clear on my next relog. I'm hoping updating deps (CCA & UC) fixes this issue. 2.1.2-beta will ship this fix.
