### ISSUE TITLE
Double Backpack Glitch

### ISSUE THREAD

**Issue by Fyoncle** [Draylar/inmis#169]
If you use trinkets, you can wear 2 backpacks in either the chestplate slot and the trinkets slot.

(I use fabric 1.20.1 but same glitch is on forge too)

**Comment by Fyoncle** [comment]
Well that is a config so, i kinda fixed it, not sure if that was intentional.

**Comment by Globox1997** [comment]
mh not really intentional.

**Comment by Fyoncle** [comment]
> mh not really intentional.

Ah then not sure why dev wasn't fixing it.
