### ISSUE TITLE
Hello Draylar!

### ISSUE THREAD

**Issue by YeZhi233** [Draylar/inmis#17]
Hello Draylar!
I'm a player from China and I think your mod is very good.
So I have translated it to Chinese, and here is the lang file:
[zh_cn.json.txt](https://github.com/Draylar/inmis/files/4721797/zh_cn.json.txt)
(I have to add ".txt" at the end to update it)

In addition,could you please allow me to repost it to the largest Minecraft forum in China [MCBBS](www.mcbbs.net)?
I'll only give the address linked to curseforge and github.

**Comment by Draylar** [comment]
Thanks for the translation! Released in [2.1.3 beta](https://github.com/Draylar/inmis/releases/tag/2.1.3-beta_1.15.2).

Yes, you are free to repost this mod on MCBBS. Thanks for asking!
