### ISSUE TITLE
update to 1.21

### ISSUE THREAD

**Issue by idkmandev** [Draylar/inmis#173]
is there an ETA?

**Comment by DracoFrostDragon** [comment]
Bumping

**Comment by Globox1997** [comment]
Updated to 1.21 with [https://github.com/Draylar/inmis/commit/54e2bf388919aa621c6acf63ab8891bd78e8825f](https://github.com/Draylar/inmis/commit/54e2bf388919aa621c6acf63ab8891bd78e8825f)

**Comment by twenty41** [comment]
The Curseforge says it only works with 1.21.1, fabric says it requires 1.21.1, plz could we get a build for base 1.21?
