### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by Dariuseluuul** [Draylar/inmis#176]
When i'm trying to craft anything while i'm using this mod alll I can craft is the base backpack and wooden buttons. I can't craft anything else

**Comment by Dariuseluuul** [comment]
![1](https://github.com/user-attachments/assets/4a7f5a6b-4a1e-4cec-9863-09957f11df40)
![2](https://github.com/user-attachments/assets/1406431d-fcb7-45a4-9064-35c05e5363c9)

**Comment by Globox1997** [comment]
Thanks for reporting, fixed with [https://github.com/Draylar/inmis/commit/f9c61ac5e93249c843ad2dcb8c1601f40a462875](https://github.com/Draylar/inmis/commit/f9c61ac5e93249c843ad2dcb8c1601f40a462875)
