### ISSUE TITLE
Cant create a workbench with spruce logs

### ISSUE THREAD

**Issue by VladIsLoviN** [Draylar/inmis#177]
Version 2.8.0 - 1.21.1
Cant create a workbench with spruce logs, also when trying to create them with green book it places only two spruce logs at the bottom but does nothing.

**Comment by Samaze123** [comment]
same here and on my server I can see lots of errors when clicking on the crafting space in the inventory.

**Comment by freddieonline** [comment]
Same issue, can't craft a crafting table with ANY form of planks, always results in crafting a button.

**Comment by lvinc71** [comment]
Same issue here. The crafting space even enables players to duplicate items. When I place two planks one above the other, the resulting craft is a button. But when I take the button, I obtain my planks, doubled.

**Comment by Globox1997** [comment]
First I thought you guys are joking xD
Fixed with [https://github.com/Draylar/inmis/commit/f9c61ac5e93249c843ad2dcb8c1601f40a462875](https://github.com/Draylar/inmis/commit/f9c61ac5e93249c843ad2dcb8c1601f40a462875)
