### ISSUE TITLE
Changing the values inside the config file gets reset upon opening Minecraft

### ISSUE THREAD

**Issue by aisukuma** [Draylar/inmis#180]
Upon changing the values inside the config for inmis, the values get reset back to its default config values.

For example, I am changing the Endless backpack's properties and the amount of slots it should have. This is an example of what I changed for it: (its in a quote because putting it in a code block does not give a desirable look)
> {
	"name": "endless",
	"rowWidth": 21,
	"numberOfRows": 6,
	"isFireImmune": true,
	"dyeable": false,
	"openSound": "minecraft:item.armor.equip_leather"
		}

However, when I save the config file and boot up Minecraft and create a new world (for testing purposes), the values do not change when I grab an Endless backpack from creative mode. I checked the config file again and the values got reset back to default.

**Comment by Globox1997** [comment]
[inmis-2.8.2-1.21.1.zip](https://github.com/user-attachments/files/16974478/inmis-2.8.2-1.21.1.zip)
Maybe try this, used gson instead of jankson here.

**Comment by aisukuma** [comment]
That worked! Thank you so much!

**Comment by maevius669** [comment]
reopen this issue, as this is not fixed yet

**Comment by MihalxCreations** [comment]
> [inmis-2.8.2-1.21.1.zip](https://github.com/user-attachments/files/16974478/inmis-2.8.2-1.21.1.zip) Maybe try this, used gson instead of jankson here.

Can we use it for modpack?
