### ISSUE TITLE
Game crashed when clicking mouse side button

### ISSUE THREAD

**Issue by linzexin022** [Draylar/inmis#20]
Hello! I found the game crashed after using the mouse side button in the Inmis bagpack GUI. Also, I found it incompatible with mod ”Inventory Profile“, which is a really nice mod for organizing and sorting inventory.
Here's the bug report
[crash-2020-06-19_12.10.57-client.txt](https://github.com/Draylar/inmis/files/4802406/crash-2020-06-19_12.10.57-client.txt)

**Comment by dandin87** [comment]
I am getting a very similar crash, Shedaniel is looking into it on teh AOF3 discord, but here is some more details. When a backpack is open you cannot drop an item to the world. The REI screen is not visible until trying to drop an item on the right side of the screen and then it opens the crafting recipe for whatever item you clicked at, but freezes for about 30 sec and then crashes. Here is my crash log, https://pastebin.com/PBd72DVG Also tested with Inmis 1.1.0 and it still crashed.

When a backpack is open there is no sort button from either invsor(inventory sorter) or invpro(inventory profiles), While this is probably unrelated and is not a feature I need, I figured I would list that I had both installed and then just invsor to try to rule out them causing problems.

**Comment by vini2003** [comment]
You can blame me for that. InventorySorter and Inventory Profiles are unlikely to work any time soon, but I can get REI working.

**Comment by linzexin022** [comment]
I think it is caused by Spinnery that Not Enough Crashes Mod had told to me. Here's another crashed report.
[crash-2020-08-02_13.15.31-client.txt](https://github.com/Draylar/inmis/files/5011705/crash-2020-08-02_13.15.31-client.txt)
