### ISSUE TITLE
Dropping a backpack ends nuking its contents

### ISSUE THREAD

**Issue by ghost** [Draylar/inmis#22]
I have been playing All of Fabric 3 1.0.0 and I ended discovering a bug where dropping a backpack in the ground ends erasing all its contents, leaving it completely empty. The mod version is 2.1.3-beta.

**Comment by Draylar** [comment]
It seems to be an issue with either CCA or Universal Components. I'm assuming you're using 1.0.0 release (2.1.3-beta was for pre2)? I don't think 2.1.3-beta will launch on 1.16 release. I was able to use 2.1.3-beta fine, but 1.16 pickup also broke for me. I'm waiting to see if CCA can push a fix, and then I'll re-release the 1.16 version.

Thanks for the report! (issue: https://github.com/OnyxStudios/Cardinal-Components-API/issues/30)

**Comment by Draylar** [comment]
Fixed in 1.0.2 ([CF](https://www.curseforge.com/minecraft/mc-mods/inmis/files/2988043), [GH](https://github.com/Draylar/inmis/releases/tag/1.0.2-1.16)).
