### ISSUE TITLE
problem with new fabric version

### ISSUE THREAD

**Issue by Gh0st0rchid** [Draylar/inmis#23]
i know you literally just uploaded the new version and i went to test it but i get a crash due to this mod
[crash-2020-07-03_21.48.00-client.txt](https://github.com/Draylar/inmis/files/4871282/crash-2020-07-03_21.48.00-client.txt)

**Comment by Draylar** [comment]
This is OptiFine's fault and is not something I can fix. It is conflicting with [CCA](https://github.com/OnyxStudios/Cardinal-Components-API) (see the [pinned issue](https://github.com/Draylar/inmis/issues/10) for more information), which is a mod I depend on (but it is not their fault either). The only option would be opening an issue on the OptiFabric repository to see if modmuss can patch the issue (but my personal recommendation would be ditching OptiFine and trying something like [Phosphor](https://www.curseforge.com/minecraft/mc-mods/phosphor), [Lithium](https://www.curseforge.com/minecraft/mc-mods/lithium), or the upcoming [Sodium](https://github.com/jellysquid3/sodium-fabric)).
