### ISSUE TITLE
Add Netherite Backpack

### ISSUE THREAD

**Issue by Ayutac** [Draylar/inmis#26]
From one of my recent adventures I made a stupid mistake (again) and fell down in the nether and died (again), some lava gobbling up my backpack (first time, I swear). So why not add a netherite backpack using the smithing table and a netherine ingot?

I would also propose that it is only to be applied to the bejeweled backpack (because that fits the vanilla style of adding netherite to diamond tools) and doesn't change the inventory size, so players have to decide to go for either lava proof or big space, adding a bit of diversity to the current bigger=better theme of your mod :)

**Comment by Draylar** [comment]
I just added the _Blazing Backpack_ in 1.2.0, which is fire-immune (but is a separate crafting tree from withered/endless). Might change it to require the smithing table later (was just opting more for the Magma theme instead of Netherite).
