### ISSUE TITLE
Crash opening backpacks on Spinnery 3.0.54?

### ISSUE THREAD

**Issue by graeye** [Draylar/inmis#27]
**Setup**

- Minecraft 1.16.1
- Fabric API: fabric-api-0.14.1+build.372-1.16.jar
- Fabric Language Kotlin: fabric-language-kotlin-1.3.71+build.1.jar
- Astromine: astromine-1.0.31+fabric-1.16.1.jar
- inmis: inmis-1.1.1-1.16.1.jar
- Pack: All of Fabric 3, modified.
- Crash report: https://pastebin.com/DeSfRWYM

**Problem**

- Astromine, as of version 1.0.31, is referencing Spinnery 3.0.54. With this version loaded, opening a backpack immediately crashes the game. Changing back to Astromine 1.0.25, referencing Spinnery 3.0.48, with no other changes, does not crash while opening backpacks.

**Reproduction**

- Open backpack in hotbar. Tier/type of backpack doesn't appear to matter.

**Remarks**

- Let me know if I can provide more information to assist, or if I should open this issue elsewhere.

Thanks!

**Comment by Draylar** [comment]
Fixed in 1.2.0. Thank you for the detailed report!
