### ISSUE TITLE
Will this mod be compatible with Trinkets and Inventory Profiles?

### ISSUE THREAD

**Issue by Etherrrr** [Draylar/inmis#28]
Hello, inmis is a very useful mod and I really like it.
But when I played a game with `All Of Fabric 3` modpack it seems conflict with Trinkets and Inventory Profiles...
The backpack cannot be equipped in the chest:backpack slot.
Items in the backpack cannot be sorted by Inventory Profiles, and different piles cannot be merged automatically(e.g. if a pile of 10 iron ingots was placed in the backpack, when you put next group of iron ingots holding `SHIFT`, the new ingots will be placed in another slot...)

Are these incompatible issues? Will it be supported in the following versions?

Thanks a lot.

**Comment by Draylar** [comment]
The shift-clicking issue is on [Spinnery](https://github.com/vini2003/Spinnery), and from my understanding, it's already on the to-do list. Trinket compatibility like that isn't something I have considered up to this point, but I'll look into it.

**Comment by Etherrrr** [comment]
Thanks a lot!
