### ISSUE TITLE
Player able to click on menus behind the backpack screen

### ISSUE THREAD

**Issue by Br00t4L17y** [Draylar/inmis#30]
**Issue**:
While a backpack is open, player is able to click through the screen to select menus in the background.

**Steps to reproduce**:
1. Open backpack
2. Click on the right side of the screen where REI is (which closes the backpack and brings up a recipe screen)
3. Press escape to close recipe screen
4. Game crashes

**Proposed solution**:
Disable the player from being able to click on things behind the backpack screen while the backpack is open. (escape key to close backpack)

`---- Minecraft Crash Report ----
// Hi. I'm Minecraft, and I'm a crashaholic.

Time: 7/29/20 10:41 AM
Description: keyPressed event handler

java.lang.ArrayIndexOutOfBoundsException

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.class_437.method_25412(class_437.java:434)

-- Affected screen --
Details:
	Screen name: me.shedaniel.rei.gui.RecipeViewingScreen
Stacktrace:
	at net.minecraft.class_437.method_25412(class_437.java:434)
	at net.minecraft.class_309.method_1466(class_309.java:348)
	at net.minecraft.class_309.method_22678(class_309.java:438)
	at net.minecraft.class_309$$Lambda$5004/446422468.run(Unknown Source)
	at net.minecraft.class_1255.execute(class_1255.java:94)
	at net.minecraft.class_309.method_22676(class_309.java:438)
	at net.minecraft.class_309$$Lambda$3651/1035383700.invoke(Unknown Source)
	at org.lwjgl.glfw.GLFWKeyCallbackI.callback(GLFWKeyCallbackI.java:37)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3101)
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:109)
	at net.minecraft.class_1041.method_15998(class_1041.java:308)
	at net.minecraft.class_310.method_1523(class_310.java:1041)
	at net.minecraft.class_310.method_1514(class_310.java:654)
	at net.minecraft.client.main.Main.main(Main.java:215)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:192)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:140)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)

-- Affected level --
Details:
	All players: 1 total; [class_746['Br00t4L17y'/338013, l='ClientLevel', x=-586.72, y=65.00, z=-2025.48]]
	Chunk stats: SodiumChunkCache: 625
	Level dimension: minecraft:overworld
	Level spawn location: World: (-256,68,-80), Chunk: (at 0,4,0 in -16,-5; contains blocks -256,0,-80 to -241,255,-65), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
	Level time: 31775566 game time, 34721614 day time
	Server brand: fabric
	Server type: Non-integrated multiplayer server

-- System Details --
Details:
	Minecraft Version: 1.16.1
	Minecraft Version ID: 1.16.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 6852311056 bytes (6534 MB) / 8589934592 bytes (8192 MB) up to 8589934592 bytes (8192 MB)
	CPUs: 8
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx8G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		adorn: Adorn 1.9.1+1.16.1
		aopalliance_aopalliance: aopalliance 1.0
		artofalchemy: Art of Alchemy 1.0.0-rc2+1.16.1
		autoconfig1u: Auto Config v1 Updated 3.2.0-unstable
		beenfo: Beenfo 1.16-fabric0.13.1-1.1
		blue_endless_jankson: jankson +
		bunch-o-trinkets: Bunch O' Trinkets 1.0.1
		cardinal-components-base: Cardinal Components API (base) 2.4.0
		cardinal-components-entity: Cardinal Components API (entities) 2.4.0-nightly.1.16-rc1.build.2
		cardinal-components-item: Cardinal Components API (items) 2.4.0
		cavebiomes: Cave Biomes 0.2.3
		cloth-basic-math: Cloth Basic Math 0.5.1
		cloth-client-events-v0: Cloth Client Events v0 1.0.4
		cloth-config2: Cloth Config v4 4.5.6
		com_electronwill_night-config_core: core 3.6.0
		com_electronwill_night-config_toml: toml 3.6.0
		com_fasterxml_jackson_core_jackson-annotations: jackson-annotations 2.9.0
		com_fasterxml_jackson_core_jackson-core: jackson-core 2.9.0
		com_fasterxml_jackson_core_jackson-databind: jackson-databind 2.9.0
		com_fasterxml_jackson_dataformat_jackson-dataformat-yaml: jackson-dataformat-yaml 2.9.0
		com_fasterxml_jackson_module_jackson-module-kotlin: jackson-module-kotlin 2.9.0
		com_github_therandomlabs_trlutils-config: TRLUtils-Config master-SNAPSHOT
		com_github_therandomlabs_trlutils-fabric: TRLUtils-Fabric 1.16-SNAPSHOT
		com_google_inject_guice: guice 4.2.3
		cotton: Cotton 1.0.5
		cotton-cauldron: Cotton Cauldron 1.0.4
		cotton-commons: Cotton Commons 1.0.4
		cotton-config: Cotton Config 1.0.0-rc.7
		cotton-datapack: Cotton Datapack 1.0.5
		cotton-logging: Cotton Logging 1.0.0-rc.4
		cotton-player-events: Cotton Player Events 1.0.2
		essentials-base: Essentials 0.2.3+1.16.1
		extraalchemy: Extra Alchemy 1.0.3
		fabric: Fabric API 0.14.1+build.372-1.16
		fabric-api-base: Fabric API Base 0.1.3+12a8474c7c
		fabric-biomes-v1: Fabric Biomes (v1) 0.2.7+059ea86602
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.4+c6a8ea8902
		fabric-command-api-v1: Fabric Command API (v1) 1.0.8+5ce5339802
		fabric-commands-v0: Fabric Commands (v0) 0.2.0+52d3083602
		fabric-containers-v0: Fabric Containers (v0) 0.1.8+045df74f02
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.1.9+059ea86602
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.2+b7f9825d02
		fabric-diagonal-panes: Fabric Diagonal Panes 0.3.0
		fabric-dimensions-v1: fabric-dimensions-v1 1.0.0+a71b305302
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.3.3+7066030f02
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.0+16acbe5b02
		fabric-item-api-v1: Fabric Item API (v1) 1.0.0+16acbe5b02
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.0+438f963602
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.0+e16a977402
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.0+3fa9f7c502
		fabric-language-kotlin: Fabric Language Kotlin 1.3.72+build.1
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.0.0+b0993bc102
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 0.1.10+059ea86602
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.2+b764ce9902
		fabric-models-v0: Fabric Models (v0) 0.1.0+dfdb52d602
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.5+b50ffc7b02
		fabric-networking-v0: Fabric Networking (v0) 0.1.10+e00ecb5f02
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.5.5+e00ecb5f02
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.6.0+da175ad602
		fabric-particles-v1: fabric-particles-v1 0.2.1+0a6f2a7002
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.3.8+7dba2d6c02
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.2.13+eae12eb802
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.3.2+4d66bed502
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 2.0.1+5a0f9a6002
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.3+b7f9825d02
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.8+b7084faa02
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.0+5341049002
		fabric-rendering-v1: Fabric Rendering (v1) 1.1.2+346247d702
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.2.6+f41e209802
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.0.1+f362c86e02
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 0.2.7+a4c57d8e02
		fabric-textures-v0: Fabric Textures (v0) 1.0.4+eae12eb802
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.1.4+5794386e02
		fabricloader: Fabric Loader 0.9.0+build.204
		glassdoor: Glass Doors 1.4.4-1.16
		glassential: Glassential 1.16.1-1.1.4
		gubbins: Gubbins 1.1.1-1.16.1
		inmis: Inmis 1.1.1-1.16.1
		inventorysorter: Inventory Sorter 1.7.0-1.16
		jankson: Jankson 3.0.0+j1.2.0
		javax_inject_javax_inject: javax.inject 1
		kyrptconfig: Kytpt Config 1.0.4-1.16
		libcd: LibCapableData 2.4.1+1.16-pre2
		libgui: LibGui 2.0.1+1.16.1
		libstructure: Libstructure 1.3
		lithium: Lithium 0.5.0
		minecraft: Minecraft 1.16.1
		modmenu: Mod Menu 1.12.2+build.17
		mysql_mysql-connector-java: mysql-connector-java 5.1.46
		org_javassist_javassist: javassist 3.26.0-GA
		org_jetbrains_annotations: annotations 17.0.0
		org_jetbrains_exposed_exposed-core: exposed-core 0.23.1
		org_jetbrains_exposed_exposed-java-time: exposed-java-time 0.23.1
		org_jetbrains_exposed_exposed-jdbc: exposed-jdbc 0.23.1
		org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.3.72
		org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.3.72
		org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.3.72
		org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.3.72
		org_jetbrains_kotlinx_kotlinx-coroutines-core: kotlinx-coroutines-core 1.3.7
		org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.3.7
		org_postgresql_postgresql: postgresql 42.2.2
		org_reflections_reflections: reflections 0.9.12
		org_slf4j_slf4j-api: slf4j-api 1.8.0-beta1
		org_xerial_sqlite-jdbc: sqlite-jdbc 3.28.0
		org_yaml_snakeyaml: snakeyaml 1.26
		parchment: Parchment 1.0.2+1.15.2
		phosphor: Phosphor 0.6.0+build.7
		playerabilitylib: Pal 1.2.0
		reach-entity-attributes: Reach Entity Attribute 1.0.1
		reborncore: Reborn Core 4.3.1+build.35
		roughlyenoughitems: Roughly Enough Items 4.7.0
		shapes: Shapes 2.0.0+build.10
		sodium: Sodium 0.1.0
		soulbound: Soulbound 1.0.1
		spinnery: Spinnery 3.0.48
		step-height-entity-attribute: Step Height Entity Attribute 1.0.0
		team_reborn_energy: Energy 0.1.0
		techreborn: Tech Reborn 3.4.2+build.48
		terraform: Terraform 2.1.6+build.30
		terrestria: Terrestria 2.0.2+build.29
		trinkets: Trinkets 2.6.2
		universalcomponents: Universal Components 0.7.2+1.16-pre2
		vanilladeathchest: VanillaDeathChest 1.16.1-1.11.0.3-fabric
		voxelmap: VoxelMap 1.10.4
		waila: Hwyla 1.9.22
		winged: Winged Mod 1.16-1.2
	Launched Version: fabric-loader-0.9.0+build.204-1.16.1
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: Radeon RX 570 Series GL version 4.6.13559 Compatibility Profile Context 26.20.12028.2, ATI Technologies Inc.
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Resource Packs: vanilla, virtual/fabric-diagonal-panes:models
	Current Language: English (US)
	CPU: 8x Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz`

**Comment by Draylar** [comment]
You have an outdated version of Inmis. [Update to 2.0.0](https://github.com/Draylar/inmis/releases/tag/1.2.0-1.16.1) and let me know if the issue persists. Your REI version is also slightly outdated (4.7 vs 4.10), so you might also want to try updating that. I'm able to view REI recipes from a backpack GUI without a crash in my development environment.
