### ISSUE TITLE
Config doesn't affect existing worlds

### ISSUE THREAD

**Issue by G93d14** [Draylar/inmis#31]
Hey I modified the config file to increase the storage space, as you do, but the world I already had going before I installed the mod still shows the previous space...

**Comment by G93d14** [comment]
Okay I just checked with a new world too, the same issue is there. Your config file just doesn't seem to acrually affect your items in-game.

**Comment by G93d14** [comment]
![Annotation 2020-07-30 105515](https://user-images.githubusercontent.com/54314688/88884034-56498a00-d253-11ea-8d23-c339da6f5d57.png)

**Comment by Draylar** [comment]
Works fine for me on a fresh 1.16.1 install with Inmis 2.0.0 and Fabric API. Did you save the file (while the game is _not_ running), and then start your game? You will need to fully restart your client for the changes to take effect. Can you also post a game log?

![image](https://user-images.githubusercontent.com/17728338/88970405-f87b6900-d277-11ea-9d08-4d023de2f397.png)


![image](https://user-images.githubusercontent.com/17728338/88970368-ebf71080-d277-11ea-98b6-e0794679792c.png)

**Comment by G93d14** [comment]
I had disabled the mod in MultiMC, I'll change the configs and enable the
mod again and see if that fixes it. I'll also look for the game logs in my
system, but I'm not sure where MultiMC saves them. Thanks!

**Comment by G93d14** [comment]
Deleting and reloading the config file fixed it, thank you!
