### ISSUE TITLE
Blazing Backpack isn't showing up

### ISSUE THREAD

**Issue by Etherrrr** [Draylar/inmis#33]
After update the mod, the Blazing Backpack isn't showing up in any mod or in the REI.

Tested with only inmis installed.

**Comment by Draylar** [comment]
Post yer game log to [hastebin](https://hastebin.com/).

**Comment by Etherrrr** [comment]
the log file is [here](https://hastebin.com/obebomacil.md)

**Comment by Draylar** [comment]
Can you delete the Inmis config file (`config/inmis.json`) and try again?

**Comment by Etherrrr** [comment]
it works!
Thanks a lot!

Hope for the translation updating
