### ISSUE TITLE
Missing Id's when trying to join Fabric Server

### ISSUE THREAD

**Issue by braxten509** [Draylar/inmis#38]
When I try to join the server, if the minecraft instance and server instance don't have the same config, it gives a list of different ID's that are missing, just being the blazing backback. I managed to make it work by just cloning the config, but I thought I'd let you know.

**Comment by Draylar** [comment]
Yes, there's nothing much I can do about this issue. Thank you for letting me know, though (first time hearing of it).

Items _have_ to be registered while the game is loading: no exceptions. If the client doesn't register an item by the time it attempts to connect to a server, it's too late. This means most potential solutions (like syncing server config to the client) simply won't work. 

The only possible solution I can think of is having _all_ backpacks under the same ID, but I would never actually do that. There are a few other solutions that might be possible in future updates (would need dynamic item registries, similar to the new .json biomes/features), but those are a long way off.

**Comment by braxten509** [comment]
Ah, you're welcome. Good to know!
