### ISSUE TITLE
Bug when putting the backpack into the backpack

### ISSUE THREAD

**Issue by linzexin022** [Draylar/inmis#40]
Hi there, I found that If I put A backpack (except ender backpack) into B backpack, drop B backpack to the ground, then A backpack will disappear.

**Comment by Caridmum** [comment]
Also found this, A backpack will also disappear if the B backpack is simply moved to another inventory slot.

**Comment by pett-j** [comment]
I can add to this issue,

Putting B into A makes B disappear..

**Comment by Draylar** [comment]
1.3.1 makes it so you can't (easily) place backpacks into other backpacks. I didn't touch the clear bug (so don't _try_ to put it in), so I will attempt to fully patch it if people still figure out how to get past the slot locks.

**Comment by kotx** [comment]
> 1.3.1 makes it so you can't (easily) place backpacks into other backpacks. I didn't touch the clear bug (so don't _try_ to put it in), so I will attempt to fully patch it if people still figure out how to get past the slot locks.

@Draylar hey, it seems like you just blocked moving the backpack item with a mouse. However pressing number keys like 1 2 3 etc. isn't canceled. The server crashes with StackOverflowError when the client attempts this. 

Repro steps:
1. Place an item in a backpack
2. Hover over the item
3. Press a hotbar swapping key to swap the item and the backpack in the hotbar slot.

**Comment by Draylar** [comment]
Please provide your server game log through your text file sharing tool of choice.

**Comment by kotx** [comment]
> Please provide your server game log through your text file sharing tool of choice.

My bad, seems to work on the latest version. My client and server versions were out of sync.
