### ISSUE TITLE
Gui and sorting issues

### ISSUE THREAD

**Issue by TimelapsedEon** [Draylar/inmis#41]
1.16.1 Seems to not play well with Inventory Sorter by kryptonaught and places the sort buttons in an unusual position. I have also experienced many issues putting items into bags and not shift-clicking into a stack with identical items. Recommendations? (I cannot update to 1.16.2+)

**Comment by Draylar** [comment]
Spinnery has a lot of sorting/shift-clicking issues. 1.16.2 fixes this with a total rewrite of the GUIs, but I don't have any plans to backport the changes.
