### ISSUE TITLE
Backpack deleting items upon teleport

### ISSUE THREAD

**Issue by NotPiffany** [Draylar/inmis#42]
My bejeweled backpack deletes everything inside when I teleport or go to and from the Nether (haven't been to the End yet in this pack). I'm on All of Fabric 3 2.0.5

**Comment by Draylar** [comment]
[Having trouble reproducing this.](https://streamable.com/6ea2xm) Was there anything I missed in that clip? Is AOF3 on 1.3.0 for Inmis?

**Comment by gomsoop** [comment]
I think it is using /tp command. I had this same issue, and thought it was gamemode issue(as I was going through creative, spectator, and survival). Also, Xaeros Minimap uses teleport.

**Comment by Draylar** [comment]
Feel free to re-open this issue if you encounter it again.
