### ISSUE TITLE
INMIS Causing Creative Mode Inventory Bug

### ISSUE THREAD

**Issue by BeardedThorgi** [Draylar/inmis#44]
On testing a server update to 1.16.3, I found that when INMIS is installed alongside a couple other mods (example: Cinderscapes), no Vanilla blocks display in Creative Mode search. There were no compatibility issues on 1.16.1 with the same set of mods. I reached out in the Discord of one of the mod groups, and they responded with this:

INMIS needs to update CCA or Curios or some library that uses CCA

**Comment by John-M87** [comment]
I am having the same issue

**Comment by JoelZBub** [comment]
Here's the bug with Cardinal Components related to this issue:
https://github.com/OnyxStudios/Cardinal-Components-API/issues/56

**Comment by Draylar** [comment]
CCA/UC has been removed in 2.0.0 beta (this is a breaking version, Backpacks will be wiped). The issue should be fixed.
