### ISSUE TITLE
switching backpack with number keys

### ISSUE THREAD

**Issue by armostsscrean** [Draylar/inmis#53]
just opened a backpack and used a number key to switch the backpack to inside of the backpack. completely crashed my game LOL

**Comment by Draylar** [comment]
Is this on 2.0.1 beta, or 2.0.0 beta (the version being used by AOF3)?

**Comment by armostsscrean** [comment]
in the 2.0.0 beta i believe

**Comment by Draylar** [comment]
2.0.1 has a fix related to locking backpack slots; it should prevent/fix your issue.

**Comment by armostsscrean** [comment]
i just updated, and it deleted all the contents of my backpacks :/ anyway to fix that?

**Comment by Draylar** [comment]
You probably updated from <2.0.0, which is why I asked what version you were on. You can not update to 2.0.0 from a previous version, it will wipe backpacks. 

I think this issue was fixed in 2.0.1-beta, but feel free to reopen it if you re-encounter the problem.
