### ISSUE TITLE
Preview?

### ISSUE THREAD

**Issue by Soggyshorts** [Draylar/inmis#56]
Is it possible to preview the bags contents like shulkers in this mod:
https://www.curseforge.com/minecraft/mc-mods/shulkerboxtooltip

Cheers!

**Comment by ChrisLensFlare** [comment]
Not the mod author but it is! They are compatible.
Cheers.

**Comment by Draylar** [comment]
Oh, forgot to close the issue... I added Shulker Box Tooltip compatibility a version or two ago. Enjoy!
