### ISSUE TITLE
Backpack disappears when backpack hotkey is pressed while in backpack.

### ISSUE THREAD

**Issue by ghost** [Draylar/inmis#60]
When you are in the backpack and press the hotkey for it while hovering over an item, the backpack disappears as it is replaced with the item you are hovering over. While this behaviour is intentional in minecraft, there should probably be some safeguard around this as you cannot get the backpack back (it's gone. forever, along with all your stored items).

**Comment by Draylar** [comment]
Is this the "open backpack" hotkey or the "swap with hotbar slot" hotkey? What version of Inmis are you using?

**Comment by ghost** [comment]
> Is this the "open backpack" hotkey or the "swap with hotbar slot" hotkey? What version of Inmis are you using?

My bad, after you mentioned which version i realised the modpack is using an outdated version. I tested with a newer version and it seems you can no longer glitch it out, it was probably fixed in a newer release.

Thanks for the response :)
