### ISSUE TITLE
[Request] Unstackables Only

### ISSUE THREAD

**Issue by ghost** [Draylar/inmis#64]
Sorry if this is the wrong place to ask this, but I was wondering if there could be a version of this mod where the backpacks can only contain unstackable items? Things like discs, saddles, enchantment books, potions, etc. I think that'd be a good way to balance for some modlists! You could go out mining and put your "goodies" into your backpack. This could also be neat as a config option like "unstackablesOnly" or "noStackables"

I've gotten this idea from a video called ["Why Bundles Don't Fix the Inventory Issue"](https://www.youtube.com/watch?v=_OYXG8dKmcI)

Thank you!

**Comment by Draylar** [comment]
Out in the next release! Enable the `unstackablesOnly` option in `inmis.json` to utilize it.
