### ISSUE TITLE
Crashing 

### ISSUE THREAD

**Issue by Restless1304** [Draylar/inmis#66]
Hey there, I've been crashing on the launcher screen and I'm not sure how to fix it .I've check to see if it was Optifabric to see if it has been causing any problems but it hasn't been(I removed it from the mods and loaded it up and still crashing) and I've also redownloaded the mod just in case but I'm still getting the crash report so if you could help me with it, I'd appreciate it.

**Comment by Restless1304** [comment]
[crash-2021-02-27_19.31.40-client.txt](https://github.com/Draylar/inmis/files/6055256/crash-2021-02-27_19.31.40-client.txt)
No Optifabric
[crash-2021-02-27_19.32.43-client.txt](https://github.com/Draylar/inmis/files/6055262/crash-2021-02-27_19.32.43-client.txt)
With Optifabric

**Comment by Draylar** [comment]
Could you try deleting the inmis config file (inmis.json) in your config directory?

**Comment by Restless1304** [comment]
Thank you for the help its now working again 👍
