### ISSUE TITLE
Crash when I load up Minecraft from the launcher

### ISSUE THREAD

**Issue by EasyCanadianGamer** [Draylar/inmis#71]
Hey! So I was getting a crash report about the initialization of the game and then it says that there was an  error about the initialization of inmis.  This is the crash report. I get the same report with and without Optifabric. 
[crash-2021-04-05_15.05.03-client.txt](https://github.com/Draylar/inmis/files/6260160/crash-2021-04-05_15.05.03-client.txt)

**Comment by Draylar** [comment]
Thanks for the report & log, fixed in 2.2.1~
