### ISSUE TITLE
Crash after updating to version 2.2.0

### ISSUE THREAD

**Issue by cerealconjugo** [Draylar/inmis#72]
[crash-2021-04-05_15.12.21-client.txt](https://github.com/Draylar/inmis/files/6260911/crash-2021-04-05_15.12.21-client.txt)

At first I thought that the last update was incompatible with some of the other mods that I have installed, but I tried it alone and it still crashes. Also check if it was the Java version, but it crashed with all the ones I tried, 8, 11, 15 and 16, all crash.
(Sorry for the bad inglish)

**Comment by Draylar** [comment]
Fixed in 2.2.1, thank you for the report & crash log :)
