### ISSUE TITLE
Shulker Boxes: Blacklisted? No.

### ISSUE THREAD

**Issue by XVOMercy** [Draylar/inmis#75]
Shulker boxes are blacklisted- so yay. But not the colored ones- which kind of ruins the whole point. Please make it so that colored shulkers are blacklisted. :)

Here's the image of me being unable to put shulkers- but being able to put colored shulkers. Thanks!
![Capture](https://user-images.githubusercontent.com/26396642/117309894-ddfe9d80-ae50-11eb-9ac2-bc2e65568ff4.PNG)
![Capture2](https://user-images.githubusercontent.com/26396642/117309896-de973400-ae50-11eb-9416-29450dbb1d50.PNG)

**Comment by marconovino** [comment]
shhh!! 

If the dev fixes the issue it would be nice to add some config option to allow shulkers

**Comment by Draylar** [comment]
Fixed in the next release - you can also use `disableShulkers` to turn it off if you'd like :)
