### ISSUE TITLE
Plans for 1.17?

### ISSUE THREAD

**Issue by bentterp** [Draylar/inmis#77]
Hi!
Just wanted to hear if you have plans to update for 1.17? RC1 is out now so we shouldn't expect significant changes.

Happy to test if that's any help

**Comment by Draylar** [comment]
Just pushed a 1.17 release. Let me know if you encounter any issues!

**Comment by bentterp** [comment]
Works perfect AFAICT. I've created 2 frayed 'packs and put different things in them, then upgraded to plated and gilded without any issues

Thank you very much
