### ISSUE TITLE
mod crash with others

### ISSUE THREAD

**Issue by zBONNELESz** [Draylar/inmis#8]
https://gist.githubusercontent.com/Cloak-Bot/6dac0fe68cfb7068aabc38d3c6d7c591/raw/5175ff59e83c96b7c58fdf2bd7efd9d8f72a71a0/crash.txt

**Comment by Draylar** [comment]
The log seems to suggest it's a Cardinal Components issue... does it work without Optifabric/Optifine?

**Comment by zBONNELESz** [comment]
tanks
