### ISSUE TITLE
The game crashed whilst initializing game Error: java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'inmis'! Exit Code: -1

### ISSUE THREAD

**Issue by Aeinbeatwo** [Draylar/inmis#82]
Keeps on crashing but whenever I remove inmis it works|
Crash Report:
[crash-2021-05-03_13.17.51-client.txt](https://github.com/Draylar/inmis/files/6731501/crash-2021-05-03_13.17.51-client.txt)

**Comment by Draylar** [comment]
Try deleting the inmis config file inside your `config` directory (probably `inmis.json`), and then launch again.

**Comment by Aeinbeatwo** [comment]
> Try deleting the inmis config file inside your `config` directory (probably `inmis.json`), and then launch again.

Thank you it works!
