### ISSUE TITLE
Enchantment code isnt working properly (I think)

### ISSUE THREAD

**Issue by marconovino** [Draylar/inmis#83]
So im using Dark Enchanting, a mod that lets you enchant items with what you want at the cost of xp. This mod works with all the other modded items I have, but backpacks arent working, i contacted the dev of dark enchanting and he told me it was your code that wasnt interfacing correctly not the dark enchanting code. Can you look into the issue?

**Comment by Draylar** [comment]
Inmis backpacks have never been enchantable (even through standard mechanics). What are you trying to enchant them with?
