### ISSUE TITLE
Opening backpack crash

### ISSUE THREAD

**Issue by Zank82** [Draylar/inmis#86]
Updated a bunch of mods on an existing world not even sure yours was one of them. when I try to open my backpack this crashes world. [Pastebin](https://pastebin.com/0TfsiTf1)
Edit: fixed link

**Comment by Zank82** [comment]
ok this is weird, I disabled Mo'Colors Mod which I've had right along and now I can open the backpack. I guess I had their paint tool in the backpack.

**Comment by Draylar** [comment]
Feel free to re-open the issue if you encounter the crash again.
