### ISSUE TITLE
Endless Backpack Causes Immediate Crahes.

### ISSUE THREAD

**Issue by jetstrike** [Draylar/inmis#89]
Log: https://pastebin.com/hhDEKp14

Anytime the endless backpack exists in your inventory you will crash immediately.

**Comment by Draylar** [comment]
I don't think this is an Inmis issue; guessing an item in your backpack is causing the game to crash when it renders, or it has something to do with your modified Aristois client. Feel free to re-open the issue if you can reproduce it without other mods.
