### ISSUE TITLE
Backpacks lose all contents when upgrading

### ISSUE THREAD

**Issue by Boundarybreaker** [Draylar/inmis#9]
Upgrading a backpack causes it to lose all its previous contents, due to JSON recipes not carrying over NBT. The two best solutions are to add a custom `ShapedRecipe` subclass that does the NBT carrying, or use NBT crafting.

**Comment by Draylar** [comment]
Fixed in 8b098b29ae89ed270845abff89c44e1a31f413af. Thanks!
