### ISSUE TITLE
Backpack will crash the game when I open them (Im playing on a server)

### ISSUE THREAD

**Issue by phumgum** [Draylar/inmis#92]
Its my server, and I made sure inmis was there, so it is there, so that's not the problem, but if you need it, here's the crash report.
https://docs.google.com/document/d/1uYIO37DD4QirBhtl8VhZZUDwFK96wpZM3NO0-neAuPc/edit?usp=sharing if you could help me fix this, that would be great.

**Comment by Draylar** [comment]
You're using 1.16.5 Inmis on a 1.17.1 server. [Update to this version](https://www.curseforge.com/minecraft/mc-mods/inmis/files/3452481) and it should work. Let me know if you encounter any other issues! :)
