### ISSUE TITLE
crashing on launch

### ISSUE THREAD

**Issue by pranav11052002** [Draylar/inmis#99]
the mod is crashing the game along with the following mods.
acmes
architectury
balm fabric
betterF3
clothconfig
fabric API
modmenu
mouse-wheelie
optifabric
optifine pre HD_U_H37(1.18)
simple voice chat
waystones fabric
wthit
minecraft capes
error report 
[crash-2021-12-10_18.42.45-client  123.txt](https://github.com/Draylar/inmis/files/7692955/crash-2021-12-10_18.42.45-client.123.txt)

**Comment by Draylar** [comment]
You'll need to update Fabric API to 0.44.0+1.18... I would send you a download link, but CurseForge seems to be down.

I will keep this issue open so I remember to add a dependency in fabric.mod.json so the issue is easier to figure out in the future. Thanks for letting me know.
